### ISSUE TITLE
selectButton returns nil always

### ISSUE THREAD

**Issue by rugmangathan** [shamasshahid/SSRadioButtonsController#4] opened 2015-06-24 07:49 UTC
currentSelectedButton now returns nil always.
i have used a buttonOutletCollection.

radioButtonGroup.setButtonsArray(bloodGroupButton)

func didButtonGroupSelected(sender: UIButton) {
var control = radioButtonGroup.selectedButton()
print(control) //prints nil
}

**Comment by shamasshahid** [comment] 2015-06-24 07:49
@RMK19 This was an issue earlier on and was fixed. Are you using latest build?

**Comment by rugmangathan** [comment] 2015-06-24 07:53
I'm using the latest build. i think in SSRadioButtonsController curretSelectedButton initiated to nil but never assigned a button to it.

**Comment by shamasshahid** [comment] 2015-06-24 08:00
@RMK19 I just pushed a fix to master. Please test it and let me know if it fixes the issue for you.

**Comment by rugmangathan** [comment] 2015-06-24 08:10
@shamasshahid  Not working as it becomes nil in removeButton method

**Comment by shamasshahid** [comment] 2015-06-24 08:20
Could you please tell me the timeline of your actions? 
You create the buttonController. Add buttons to it. The remove the selected button and it starts returning nil?

**Comment by rugmangathan** [comment] 2015-06-24 08:25
As i posted the code earlier i didn't removed the button. But it returns nil

**Comment by rugmangathan** [comment] 2015-06-24 08:31
For the first button i clicked returned nil and the second time i clicked the button got result but the selectedButton returned the previous selected button

**Comment by shamasshahid** [comment] 2015-06-24 08:34
@RMK19 I must apologize for your frustration here.
I am guessing that your `didButtonGroupSelected` is actually linked to one of the buttons that behave as RadioButtons. Right?

**Comment by rugmangathan** [comment] 2015-06-24 08:51
No, I have added target to all buttons using 
for button in groupButton {
            button.addTarget(self, action: "didButtonGroupSelected:", forControlEvents: UIControlEvents.TouchUpInside)
        }

**Comment by shamasshahid** [comment] 2015-06-24 08:56
@RMK19 That is the same too. I see the issue. 
The problem is that your `didButtonGroupSelected` is called first and `RadioButtonController`'s targets are called later.
The way I anticipated was that user will call `selectedButton()` to get the currently selectedButton to input to form values. And not by actions. 
I will try to write a delegate pattern here to accommodate for that. I will post that back here once it's done.

**Comment by rugmangathan** [comment] 2015-06-24 13:53
I solved it by making radioButtonGroup.setButtonsArray(bloodGroupButton) before adding target to those buttons and it works like a charm. Thanks :)

**Comment by shamasshahid** [comment] 2015-06-24 13:56
Awesome. Although the other issue still persists. Meanwhile, I'm going to close this issue, and will update you once I introduce delegates.

**Closed as completed by shamasshahid** 2015-06-24 13:56 UTC
