### ISSUE TITLE
Xcode crashed

### ISSUE THREAD

**Issue by milankamilya** [shamasshahid/SSRadioButtonsController#7] opened 2015-07-17 10:55 UTC
Xcode Version : 6.3
Whenever I am going build this project, Xcode stuck and on relaunch still same problem. 
I deleted the project from finder to come out this iteration.

**Comment by shamasshahid** [comment] 2015-07-17 12:22
@milankamilya Are you talking about the sample project?

**Comment by milankamilya** [comment] 2015-07-18 04:02
Yes

**Comment by shamasshahid** [comment] 2015-07-19 20:22
@milankamilya Hi Milan, I haven't been able to reproduce this at my end. Please share some logs or some way to reproduce it.

**Comment by shamasshahid** [comment] 2015-09-04 11:26
I am going to close this issue since I've been unable to reproduce it.

**Closed as completed by shamasshahid** 2015-09-04 11:26 UTC
